name: Rust Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y llvm-dev clang libclang-dev cmake ninja-build pkg-config libopencv-dev

      - name: Set Environment Variables for Clang and OpenCV
        run: |
          echo "LLVM_CONFIG_PATH=$(which llvm-config)" >> $GITHUB_ENV
          echo "LIBCLANG_PATH=$(llvm-config --libdir)" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          echo "OPENCV_INCLUDE_PATH=/usr/include/opencv4" >> $GITHUB_ENV


      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build Project
        run: cargo build --release
